from funciones.func_matriz import MetodosMatrices, DebugPrograma, OperacionesMatrices

matriz_creada = MetodosMatrices.crear_matriz()
DebugPrograma.imprimir_matriz(matriz_creada)
OperacionesMatrices.multiplicar_escalar(matriz_creada)
DebugPrograma.imprimir_matriz(matriz_creada)
OperacionesMatrices.sumar_fila_por_escalar(matriz_creada)